package com.teamopensmartglasses.augmentoslib;

public enum DataStreamType {
    CORE_SYSTEM_MESSAGE, // privileged
    TRANSCRIPTION_DEFAULT_STREAM,
    TRANSCRIPTION_ENGLISH_STREAM,
    TRANSCRIPTION_CHINESE_STREAM,
    TRANSCRIPTION_RUSSIAN_STREAM,
    TRANSCRIPTION_FRENCH_STREAM,
    TRANSCRIPTION_SPANISH_STREAM,
    TRANSCRIPTION_JAPANESE_STREAM,
    SMART_RING_BUTTON,
    GLASSES_SIDE_TAP,
    GLASSES_POV_IMAGE,
}