package com.teamopensmartglasses.augmentoslib;

public enum DataStreamType {
    CORE_SYSTEM_MESSAGE, // privileged

    TRANSCRIPTION_DEFAULT_STREAM,
    TRANSCRIPTION_ENGLISH_STREAM,
    TRANSCRIPTION_CHINESE_STREAM,
    TRANSCRIPTION_RUSSIAN_STREAM,
    TRANSCRIPTION_FRENCH_STREAM,
    TRANSCRIPTION_SPANISH_STREAM,
    TRANSCRIPTION_JAPANESE_STREAM,

    TRANSLATION_DEFAULT_STREAM,
    TRANSLATION_ENGLISH_STREAM,
    TRANSLATION_CHINESE_STREAM,
    TRANSLATION_RUSSIAN_STREAM,
    TRANSLATION_FRENCH_STREAM,
    TRANSLATION_SPANISH_STREAM,
    TRANSLATION_JAPANESE_STREAM,

    TARGET_DEFAULT_STREAM,
    TARGET_ENGLISH_STREAM,
    TARGET_CHINESE_STREAM,
    TARGET_RUSSIAN_STREAM,
    TARGET_FRENCH_STREAM,
    TARGET_SPANISH_STREAM,
    TARGET_JAPANESE_STREAM,

    SMART_RING_BUTTON,
    GLASSES_SIDE_TAP,
    GLASSES_POV_IMAGE,
}