package com.teamopensmartglasses.augmentoslib;

public enum DataStreamType {
    CORE_SYSTEM_MESSAGE, // privileged

    TRANSCRIPTION_DEFAULT_STREAM,
    TRANSCRIPTION_ENGLISH_STREAM,
    TRANSCRIPTION_SPANISH_STREAM,
    TRANSCRIPTION_RUSSIAN_STREAM,
    TRANSCRIPTION_FRENCH_STREAM,
    TRANSCRIPTION_CHINESE_STREAM,
    TRANSCRIPTION_JAPANESE_STREAM,
    TRANSCRIPTION_GERMAN_STREAM,
    TRANSCRIPTION_ARABIC_STREAM,
    TRANSCRIPTION_KOREAN_STREAM,
    TRANSCRIPTION_ITALIAN_STREAM,
    TRANSCRIPTION_TURKISH_STREAM,
    TRANSCRIPTION_PORTUGUESE_STREAM,
    TRANSCRIPTION_DUTCH_STREAM,

    TRANSLATION_DEFAULT_STREAM,
    TRANSLATION_ENGLISH_STREAM,
    TRANSLATION_SPANISH_STREAM,
    TRANSLATION_RUSSIAN_STREAM,
    TRANSLATION_FRENCH_STREAM,
    TRANSLATION_CHINESE_STREAM,
    TRANSLATION_JAPANESE_STREAM,
    TRANSLATION_GERMAN_STREAM,
    TRANSLATION_ARABIC_STREAM,
    TRANSLATION_KOREAN_STREAM,
    TRANSLATION_ITALIAN_STREAM,
    TRANSLATION_TURKISH_STREAM,
    TRANSLATION_PORTUGUESE_STREAM,
    TRANSLATION_DUTCH_STREAM,

    KILL_TRANSLATION_STREAM,

    TARGET_DEFAULT_STREAM,
    TARGET_ENGLISH_STREAM,
    TARGET_SPANISH_STREAM,
    TARGET_RUSSIAN_STREAM,
    TARGET_FRENCH_STREAM,
    TARGET_CHINESE_STREAM,
    TARGET_JAPANESE_STREAM,
    TARGET_GERMAN_STREAM,
    TARGET_ARABIC_STREAM,
    TARGET_KOREAN_STREAM,
    TARGET_ITALIAN_STREAM,
    TARGET_TURKISH_STREAM,
    TARGET_PORTUGUESE_STREAM,
    TARGET_DUTCH_STREAM,


    SMART_RING_BUTTON,
    GLASSES_SIDE_TAP,
    GLASSES_POV_IMAGE,
}