CUSTOM_USER_DATA_PATH = "./custom_data"
IMAGE_PATH = "images/cse"
SUMMARIZE_CUSTOM_DATA = True
USE_GPU_FOR_INFERENCING = True
DEFINE_RARE_WORDS = False
LLM_FILTER_THRESHOLD = 5
RELEVANCE_FILTER_TIME = 20 # number of seconds the relevance filter looks back

GPT_4_MODEL = "gpt-4-1106-preview"
GPT_4_MAX_TOKENS = 2048
GPT_TEMPERATURE = 0.5
