# Generated by Django 5.1.2 on 2024-11-21 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Actuation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('participant_id', models.CharField(default='', max_length=255)),
                ('word_id', models.CharField(default='', max_length=255)),
                ('unique_word_id', models.CharField(default='', max_length=255)),
                ('word', models.CharField(default='', max_length=255)),
                ('translation', models.CharField(default='', max_length=255)),
                ('video_index', models.IntegerField(default=0)),
                ('condition', models.IntegerField(default=0)),
                ('number_of_words_shown_at_time', models.IntegerField(default=0)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Participant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('participant_id', models.CharField(max_length=255, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('first_video', models.IntegerField(default=0)),
                ('second_video', models.IntegerField(default=0)),
                ('third_video', models.IntegerField(default=0)),
                ('conditions_video_1', models.JSONField(default=list)),
                ('conditions_video_2', models.JSONField(default=list)),
                ('conditions_video_3', models.JSONField(default=list)),
            ],
        ),
    ]
